### ISSUE TITLE
"ResolvePackageNotFound: - h5py=2.9.0l.c" Error

### ISSUE THREAD

**Issue by xixi-cathy** [marakeby/pnet_prostate_paper#2]
Hi,
I tried to create a p-net environment with "conda env create --name pnet_env --file=environment.yml", but failed. The messages are:

```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - h5py=2.9.0l.c

```
So, how to solve this problem? Thanks.

**Comment by jbansal1510** [comment]
Hi I am getting error "conda env create --name pnet_env --file=environment.yml"  any idea for this?


Pip subprocess error:
decorator requires Python '>=3.5' but the running Python is 2.7.15

failed

CondaEnvException: Pip failed
